# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170723_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 23, 13, 24, 35, 713467, tzinfo=utc)),
        ),
    ]
